export const COUNTRIES = [
  "United States",
  "Canada",
  "United Kingdom",
  "Australia",
  "Germany",
  "France",
  "India",
  "Japan",
  "Brazil",
  "Mexico",
  "China",
  "Russia",
  "South Korea",
  "Italy",
  "Spain",
  "Netherlands",
  "Switzerland",
  "Sweden",
  "Norway",
  "Denmark",
  "Belgium",
  "Austria",
  "Poland",
  "Portugal",
  "Greece",
  "Ireland",
  "New Zealand",
  "Singapore",
  "Malaysia",
  "Thailand",
  "Indonesia",
  "Philippines",
  "Vietnam",
  "Pakistan",
  "Bangladesh",
  "Nigeria",
  "South Africa",
  "Egypt",
  "Kenya",
  "Argentina",
  "Chile",
  "Colombia",
  "Peru",
  "Venezuela",
  "Turkey",
  "Saudi Arabia",
  "United Arab Emirates",
  "Israel",
  "Hong Kong",
  "Taiwan",
]

export const STATES: Record<string, string[]> = {
  "United States": [
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming",
  ],
  Canada: [
    "Alberta",
    "British Columbia",
    "Manitoba",
    "New Brunswick",
    "Newfoundland and Labrador",
    "Northwest Territories",
    "Nova Scotia",
    "Nunavut",
    "Ontario",
    "Prince Edward Island",
    "Quebec",
    "Saskatchewan",
    "Yukon",
  ],
  "United Kingdom": ["England", "Scotland", "Wales", "Northern Ireland"],
  Australia: [
    "New South Wales",
    "Queensland",
    "South Australia",
    "Tasmania",
    "Victoria",
    "Western Australia",
    "Australian Capital Territory",
    "Northern Territory",
  ],
  Germany: [
    "Baden-Württemberg",
    "Bavaria",
    "Berlin",
    "Brandenburg",
    "Bremen",
    "Hamburg",
    "Hesse",
    "Lower Saxony",
    "Mecklenburg-Vorpommern",
    "North Rhine-Westphalia",
    "Rhineland-Palatinate",
    "Saarland",
    "Saxony",
    "Saxony-Anhalt",
    "Schleswig-Holstein",
    "Thuringia",
  ],
  France: [
    "Île-de-France",
    "Provence-Alpes-Côte d'Azur",
    "Auvergne-Rhône-Alpes",
    "Nouvelle-Aquitaine",
    "Occitanie",
    "Bourgogne-Franche-Comté",
    "Brittany",
    "Centre-Val de Loire",
    "Corsica",
    "Grand Est",
    "Hauts-de-France",
    "Pays de la Loire",
  ],
  India: [
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chhattisgarh",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal",
  ],
  Japan: [
    "Tokyo",
    "Osaka",
    "Kyoto",
    "Hokkaido",
    "Fukuoka",
    "Hiroshima",
    "Nagoya",
    "Sapporo",
    "Kobe",
    "Yokohama",
    "Kawasaki",
    "Saitama",
    "Chiba",
    "Kanagawa",
    "Shizuoka",
    "Aichi",
  ],
  Brazil: [
    "São Paulo",
    "Rio de Janeiro",
    "Minas Gerais",
    "Bahia",
    "Paraná",
    "Santa Catarina",
    "Rio Grande do Sul",
    "Pernambuco",
    "Ceará",
    "Pará",
    "Goiás",
    "Maranhão",
    "Paraíba",
    "Espírito Santo",
    "Piauí",
    "Rio Grande do Norte",
    "Alagoas",
    "Mato Grosso",
    "Distrito Federal",
  ],
  Mexico: [
    "Mexico City",
    "State of Mexico",
    "Jalisco",
    "Veracruz",
    "Puebla",
    "Guanajuato",
    "Chiapas",
    "Oaxaca",
    "Sinaloa",
    "Coahuila",
    "Nuevo León",
    "Baja California",
    "Sonora",
    "Tamaulipas",
    "Yucatán",
    "Quintana Roo",
    "Morelos",
    "Querétaro",
    "Durango",
    "Zacatecas",
  ],
  China: [
    "Beijing",
    "Shanghai",
    "Guangdong",
    "Sichuan",
    "Jiangsu",
    "Zhejiang",
    "Hunan",
    "Hubei",
    "Shandong",
    "Henan",
    "Anhui",
    "Fujian",
    "Yunnan",
    "Guizhou",
    "Shaanxi",
    "Gansu",
    "Ningxia",
    "Xinjiang",
    "Tibet",
    "Qinghai",
    "Inner Mongolia",
    "Liaoning",
    "Jilin",
  ],
  Russia: [
    "Moscow",
    "Saint Petersburg",
    "Novosibirsk",
    "Yekaterinburg",
    "Nizhny Novgorod",
    "Kazan",
    "Chelyabinsk",
    "Omsk",
    "Samara",
    "Rostov",
    "Ufa",
    "Krasnoyarsk",
    "Perm",
    "Voronezh",
  ],
  "South Korea": [
    "Seoul",
    "Busan",
    "Daegu",
    "Incheon",
    "Gwangju",
    "Daejeon",
    "Ulsan",
    "Gyeonggi-do",
    "Gangwon-do",
    "North Chungcheong",
    "South Chungcheong",
    "North Jeolla",
    "South Jeolla",
    "North Gyeongsang",
    "South Gyeongsang",
    "Jeju",
  ],
  Italy: [
    "Lazio",
    "Lombardy",
    "Campania",
    "Sicily",
    "Veneto",
    "Emilia-Romagna",
    "Piedmont",
    "Tuscany",
    "Calabria",
    "Apulia",
    "Liguria",
    "Marche",
    "Abruzzo",
    "Molise",
    "Umbria",
    "Sardinia",
    "Friuli-Venezia Giulia",
    "Trentino-Alto Adige",
    "Basilicata",
    "Aosta Valley",
  ],
  Spain: [
    "Madrid",
    "Barcelona",
    "Valencia",
    "Seville",
    "Bilbao",
    "Malaga",
    "Murcia",
    "Palma",
    "Las Palmas",
    "Alicante",
    "Cordoba",
    "Valladolid",
    "Zaragoza",
    "Gijón",
    "Eibar",
  ],
  Netherlands: [
    "North Holland",
    "South Holland",
    "Utrecht",
    "Gelderland",
    "Overijssel",
    "Flevoland",
    "Friesland",
    "Groningen",
    "Drenthe",
    "Limburg",
    "North Brabant",
  ],
  Switzerland: [
    "Zurich",
    "Bern",
    "Lucerne",
    "Uri",
    "Schwyz",
    "Obwalden",
    "Nidwalden",
    "Glarus",
    "Zug",
    "Fribourg",
    "Solothurn",
    "Basel-Landschaft",
    "Basel-Stadt",
    "Schaffhausen",
    "Appenzell Ausserrhoden",
    "Appenzell Innerrhoden",
    "St. Gallen",
    "Graubünden",
    "Aargau",
    "Thurgau",
    "Ticino",
    "Vaud",
    "Valais",
    "Neuchâtel",
    "Jura",
    "Geneva",
  ],
  Sweden: [
    "Stockholm",
    "Västra Götaland",
    "Skåne",
    "Uppland",
    "Södermanland",
    "Östergötland",
    "Värmland",
    "Örebro",
    "Gävleborg",
    "Västernorrland",
    "Jämtland",
    "Västerbotten",
    "Norrbotten",
    "Dalarna",
    "Gotland",
  ],
  Norway: [
    "Oslo",
    "Akershus",
    "Hordaland",
    "Sogn og Fjordane",
    "Møre og Romsdal",
    "Sør-Trøndelag",
    "Nord-Trøndelag",
    "Nordland",
    "Troms",
    "Finnmark",
    "Oppland",
    "Hedmark",
    "Buskerud",
    "Telemark",
    "Aust-Agder",
    "Vest-Agder",
    "Rogaland",
    "Hordaland",
  ],
  Denmark: ["Capital Region", "Zealand", "Southern Denmark", "Central Denmark", "North Denmark"],
  Belgium: [
    "Brussels",
    "Antwerp",
    "Limburg",
    "East Flanders",
    "West Flanders",
    "Flemish Brabant",
    "Walloon Brabant",
    "Liège",
    "Namur",
    "Hainaut",
    "Luxembourg",
  ],
  Austria: [
    "Vienna",
    "Lower Austria",
    "Upper Austria",
    "Salzburg",
    "Tyrol",
    "Vorarlberg",
    "Carinthia",
    "Styria",
    "Burgenland",
  ],
  Poland: [
    "Masovia",
    "Silesia",
    "Greater Poland",
    "Lesser Poland",
    "Łódź",
    "Pomerania",
    "Kuyavia-Pomerania",
    "Warmia-Masuria",
    "Subcarpathia",
    "Podlaskie",
    "Opole",
    "Lower Silesia",
    "West Pomerania",
    "Holy Cross",
  ],
  Portugal: [
    "Lisbon",
    "Porto",
    "Braga",
    "Covilhã",
    "Aveiro",
    "Covilhã",
    "Guarda",
    "Leiria",
    "Santarém",
    "Castelo Branco",
    "Portalegre",
    "Évora",
    "Beja",
    "Faro",
    "Madeira",
    "Azores",
  ],
  Greece: [
    "Attica",
    "Central Macedonia",
    "Western Macedonia",
    "Thessaly",
    "Ionian Islands",
    "Western Greece",
    "Central Greece",
    "Peloponnese",
    "North Aegean",
    "South Aegean",
    "Crete",
  ],
  Ireland: [
    "Dublin",
    "Cork",
    "Galway",
    "Limerick",
    "Waterford",
    "Tipperary",
    "Kilkenny",
    "Carlow",
    "Wexford",
    "Wicklow",
    "Kildare",
    "Meath",
    "Louth",
    "Monaghan",
    "Cavan",
    "Leitrim",
    "Roscommon",
    "Longford",
    "Westmeath",
    "Offaly",
    "Laois",
    "Kilkenny",
    "Sligo",
    "Mayo",
  ],
  "New Zealand": [
    "Auckland",
    "Wellington",
    "Christchurch",
    "Hamilton",
    "Tauranga",
    "Lower Hutt",
    "Dunedin",
    "Palmerston North",
    "Rotorua",
    "Napier",
    "Hastings",
    "New Plymouth",
  ],
  Singapore: ["Central", "East", "North", "North-East", "West"],
  Malaysia: [
    "Kuala Lumpur",
    "Selangor",
    "Johor",
    "Penang",
    "Perak",
    "Pahang",
    "Terengganu",
    "Kelantan",
    "Kedah",
    "Perlis",
    "Negeri Sembilan",
    "Malacca",
    "Sabah",
    "Sarawak",
    "Labuan",
  ],
  Thailand: [
    "Bangkok",
    "Chiang Mai",
    "Phuket",
    "Pattaya",
    "Krabi",
    "Rayong",
    "Chon Buri",
    "Nakhon Ratchasima",
    "Khon Kaen",
    "Udon Thani",
    "Chiang Rai",
    "Lampang",
    "Sukhothai",
  ],
  Indonesia: [
    "Jakarta",
    "Surabaya",
    "Bandung",
    "Medan",
    "Semarang",
    "Makassar",
    "Palembang",
    "Yogyakarta",
    "Malang",
    "Tangerang",
    "Depok",
    "Bekasi",
    "Bogor",
    "Batam",
    "Denpasar",
  ],
  Philippines: [
    "Metro Manila",
    "Cebu",
    "Davao",
    "Quezon City",
    "Caloocan",
    "Makati",
    "Pasig",
    "Taguig",
    "Valenzuela",
    "Paranaque",
    "Las Piñas",
    "Muntinlupa",
    "Marikina",
    "San Juan",
  ],
  Vietnam: [
    "Ho Chi Minh City",
    "Hanoi",
    "Da Nang",
    "Hai Phong",
    "Can Tho",
    "Bien Hoa",
    "Nha Trang",
    "Hue",
    "Da Lat",
    "Vung Tau",
    "Phan Thiet",
    "Quy Nhon",
    "Vinh",
    "Thai Nguyen",
  ],
  Pakistan: [
    "Karachi",
    "Lahore",
    "Faisalabad",
    "Rawalpindi",
    "Multan",
    "Hyderabad",
    "Peshawar",
    "Quetta",
    "Islamabad",
    "Gujranwala",
    "Sialkot",
    "Sargodha",
    "Bahawalpur",
    "Jhang",
  ],
  Bangladesh: ["Dhaka", "Chittagong", "Khulna", "Rajshahi", "Barisal", "Sylhet", "Rangpur", "Mymensingh"],
  Nigeria: [
    "Lagos",
    "Kano",
    "Ibadan",
    "Abuja",
    "Port Harcourt",
    "Benin City",
    "Maiduguri",
    "Zaria",
    "Oshogbo",
    "Ilorin",
    "Abeokuta",
    "Enugu",
    "Calabar",
    "Akure",
    "Ado-Ekiti",
  ],
  "South Africa": [
    "Johannesburg",
    "Cape Town",
    "Durban",
    "Pretoria",
    "Port Elizabeth",
    "Bloemfontein",
    "Pietermaritzburg",
    "Polokwane",
    "Nelspruit",
    "Kimberley",
    "Mahikeng",
    "Bisho",
  ],
  Egypt: [
    "Cairo",
    "Alexandria",
    "Giza",
    "Shubra El-Khema",
    "Helwan",
    "Port Said",
    "Suez",
    "Luxor",
    "Aswan",
    "Mansoura",
    "Tanta",
    "Asyut",
    "Ismailia",
    "Fayoum",
    "Minya",
  ],
  Kenya: [
    "Nairobi",
    "Mombasa",
    "Kisumu",
    "Nakuru",
    "Eldoret",
    "Kericho",
    "Nyeri",
    "Muranga",
    "Thika",
    "Machakos",
    "Naivasha",
    "Isiolo",
    "Garissa",
    "Lamu",
    "Malindi",
    "Kilifi",
  ],
  Argentina: [
    "Buenos Aires",
    "Córdoba",
    "Rosario",
    "Mendoza",
    "La Plata",
    "Mar del Plata",
    "Salta",
    "San Juan",
    "Santa Fe",
    "Tucumán",
    "Santiago del Estero",
    "Corrientes",
  ],
  Chile: [
    "Santiago",
    "Valparaíso",
    "Concepción",
    "La Serena",
    "Temuco",
    "Valdivia",
    "Puerto Montt",
    "Punta Arenas",
    "Antofagasta",
    "Iquique",
    "Coquimbo",
    "Talca",
    "Chillán",
  ],
  Colombia: [
    "Bogotá",
    "Medellín",
    "Cali",
    "Barranquilla",
    "Cartagena",
    "Cúcuta",
    "Bucaramanga",
    "Santa Marta",
    "Ibagué",
    "Pereira",
    "Armenia",
    "Manizales",
    "Villavicencio",
    "Pasto",
  ],
  Peru: [
    "Lima",
    "Arequipa",
    "Trujillo",
    "Chiclayo",
    "Iquitos",
    "Cusco",
    "Ayacucho",
    "Huancayo",
    "Pucallpa",
    "Tacna",
    "Juliaca",
    "Piura",
    "Chimbote",
    "Huacho",
    "Chincha",
  ],
  Venezuela: [
    "Caracas",
    "Maracaibo",
    "Valencia",
    "Barquisimeto",
    "Maracay",
    "Ciudad Guayana",
    "Mérida",
    "Puerto La Cruz",
    "San Cristóbal",
    "Cumaná",
    "Coro",
    "Cabimas",
    "Acarigua",
  ],
  Turkey: [
    "Istanbul",
    "Ankara",
    "Izmir",
    "Bursa",
    "Antalya",
    "Gaziantep",
    "Konya",
    "Kayseri",
    "Samsun",
    "Diyarbakır",
    "Mersin",
    "Adana",
    "Eskişehir",
    "Erzurum",
    "Trabzon",
    "Rize",
  ],
  "Saudi Arabia": [
    "Riyadh",
    "Jeddah",
    "Mecca",
    "Medina",
    "Dammam",
    "Khobar",
    "Abha",
    "Tabuk",
    "Hail",
    "Buraydah",
    "Sakaka",
    "Yanbu",
    "Jubail",
    "Qatif",
    "Hofuf",
  ],
  "United Arab Emirates": ["Dubai", "Abu Dhabi", "Sharjah", "Ajman", "Umm Al Quwain", "Ras Al Khaimah", "Fujairah"],
  Israel: [
    "Tel Aviv",
    "Jerusalem",
    "Haifa",
    "Rishon LeZion",
    "Petah Tikva",
    "Ashdod",
    "Netanya",
    "Beersheba",
    "Ramat Gan",
    "Givatayim",
    "Holon",
    "Ramat Hasharon",
    "Herzliya",
    "Kfar Saba",
  ],
  "Hong Kong": ["Hong Kong Island", "Kowloon", "New Territories"],
  Taiwan: [
    "Taipei",
    "New Taipei",
    "Taichung",
    "Tainan",
    "Kaohsiung",
    "Hsinchu",
    "Taoyuan",
    "Chiayi",
    "Yunlin",
    "Changhua",
    "Nantou",
    "Miaoli",
    "Yilan",
    "Hualien",
    "Taitung",
    "Penghu",
  ],
}
